### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by yang-neu** [CVHub520/X-AnyLabeling-Server#7]
| ERROR    | app.core.registry:load_all_models | Failed to load model [yolo11n_seg]: Torch not compiled with CUDA enabled

**Comment by yang-neu** [comment]
Fixed by reinstall torch for CUDA v12.8
uv pip uninstall torch torchvision torchaudio
uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
